'use client';

import { createPortal } from 'react-dom';
import { useEffect, useMemo, useState } from 'react';
import { curriculumReadings, readingRanges } from '../lib/curriculumReadings';

const STORE = 'cfa-l1-tracker-v10';
const TOPICS = { quantitativeMethods:'Quantitative Methods', financialStatementAnalysis:'Financial Statement Analysis', fixedIncome:'Fixed Income', corporateFinance:'Corporate Finance', equities:'Equities', economics:'Economics', portfolioConstruction:'Portfolio Construction', derivativesAndRiskManagement:'Derivatives and Risk Management', alternativeInvestments:'Alternative Investments', ethics:'Ethical and Professional Standards' };
function getTopicReadings(topicId){const titles=curriculumReadings[topicId]||[];const [start]=readingRanges[topicId]||[1];return titles.map((title,index)=>({number:start+index,title}));}
function getState(){try{const raw=window.localStorage.getItem(STORE);return raw?JSON.parse(raw):{};}catch{return {};}}
function getReadingProgress(topicId,readingNumber){const progress=getState().readingProgress;const item=progress?.[topicId]?.[readingNumber];return item&&typeof item==='object'?item:null;}
function getCompletedReading(topicId){const values=getState().readingDone?.[topicId];return Array.isArray(values)?values:[];}
function updateReadingProgress(topicId,readingNumber,status){try{const state=getState();const readingProgress=state.readingProgress&&typeof state.readingProgress==='object'?{...state.readingProgress}:{};const topicProgress=readingProgress[topicId]&&typeof readingProgress[topicId]==='object'?{...readingProgress[topicId]}:{};const previous=topicProgress[readingNumber]&&typeof topicProgress[readingNumber]==='object'?topicProgress[readingNumber]:{};const incompleteCount=Number(previous.incompleteCount)||0;if(status==='incomplete'&&incompleteCount>=2)return false;const nextCount=status==='incomplete'?incompleteCount+1:incompleteCount;const history=Array.isArray(previous.history)?[...previous.history]:[];if(status==='completed')history.push({status:'completed',credit:1,at:new Date().toISOString()});else history.push({status:'incomplete',credit:nextCount===1?0.5:0.25,at:new Date().toISOString()});topicProgress[readingNumber]={status,incompleteCount:nextCount,credit:status==='completed'?1:0.5,history};readingProgress[topicId]=topicProgress;const readingDone={...(state.readingDone&&typeof state.readingDone==='object'?state.readingDone:{})};const completed=new Set(Array.isArray(readingDone[topicId])?readingDone[topicId]:[]);if(status==='completed')completed.add(readingNumber);else completed.delete(readingNumber);readingDone[topicId]=[...completed].sort((a,b)=>a-b);const topicTotal=(curriculumReadings[topicId]||[]).length;const readDone=new Set(Array.isArray(state.readDone)?state.readDone:[]);if(topicTotal>0&&completed.size===topicTotal)readDone.add(topicId);else readDone.delete(topicId);window.localStorage.setItem(STORE,JSON.stringify({...state,readDone:[...readDone],readingDone,readingProgress}));window.dispatchEvent(new CustomEvent('cfa-reading-progress-change',{detail:{topicId,readingNumber,status}}));return true;}catch{return false;}}
function setNativeValue(input,value){if(!input)return;const setter=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value')?.set;setter?.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}
export default function StudyLogReadingDialog(){
 const [open,setOpen]=useState(false),[form,setForm]=useState(null),[topicId,setTopicId]=useState('quantitativeMethods'),[readingNumber,setReadingNumber]=useState(1),[status,setStatus]=useState('completed'),[blocked,setBlocked]=useState(false);
 const readings=useMemo(()=>getTopicReadings(topicId),[topicId]);const selectedReading=readings.find(r=>r.number===readingNumber)||readings[0];const topicName=TOPICS[topicId]||topicId;
 const loadReadingState=(nextTopic,nextNumber)=>{const item=getReadingProgress(nextTopic,nextNumber);const count=Number(item?.incompleteCount)||0;setStatus(item?.status==='completed'?'completed':'incomplete');setBlocked(count>=2&&item?.status!=='completed');};
 useEffect(()=>{const attach=()=>{const targetForm=document.querySelector('.logForm');if(!targetForm||targetForm.dataset.readingDialogBound==='true')return;targetForm.dataset.readingDialogBound='true';const focusLabel=targetForm.querySelector('.wide');const focusInput=focusLabel?.querySelector('input');if(focusLabel&&focusInput){focusLabel.classList.add('readingDialogField');focusLabel.removeAttribute('data-label');Array.from(focusLabel.childNodes).forEach(node=>{if(node.nodeType===Node.TEXT_NODE)node.textContent='';});focusInput.dataset.readingFocusInput='true';focusInput.setAttribute('aria-hidden','true');focusInput.tabIndex=-1;focusInput.style.display='none';let trigger=focusLabel.querySelector('.readingDialogTrigger');if(!trigger){trigger=document.createElement('button');trigger.type='button';trigger.className='readingDialogTrigger';trigger.textContent='Choose a reading…';trigger.addEventListener('click',()=>openForForm(targetForm));focusLabel.appendChild(trigger);}}const openForForm=(target)=>{const select=target.querySelector('select');const selectedTopic=select?.value||'quantitativeMethods';const selected=getTopicReadings(selectedTopic);setTopicId(selectedTopic);setReadingNumber(selected[0]?.number||1);setForm(target);setOpen(true);loadReadingState(selectedTopic,selected[0]?.number||1);};const onSubmit=(event)=>{if(targetForm.dataset.readingDialogBypass==='true'){delete targetForm.dataset.readingDialogBypass;return;}event.preventDefault();event.stopImmediatePropagation();openForForm(targetForm);};targetForm.addEventListener('submit',onSubmit,true);targetForm._readingDialogCleanup=()=>targetForm.removeEventListener('submit',onSubmit,true);};attach();const observer=new MutationObserver(attach);observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();const targetForm=document.querySelector('.logForm');targetForm?._readingDialogCleanup?.();if(targetForm)delete targetForm.dataset.readingDialogBound;};},[]);
 useEffect(()=>{if(!readings.some(reading=>reading.number===readingNumber)){setReadingNumber(readings[0]?.number||1);return;}loadReadingState(topicId,readingNumber);},[readings,readingNumber]);
 if(!open||!form||typeof document==='undefined')return null;
 const close=()=>setOpen(false);const completed=getCompletedReading(topicId);const currentProgress=getReadingProgress(topicId,selectedReading?.number||0);const incompleteCount=Number(currentProgress?.incompleteCount)||0;
 const confirm=()=>{if(!selectedReading)return;if(status==='incomplete'&&incompleteCount>=2){setBlocked(true);return;}const subjectSelect=form.querySelector('select');if(subjectSelect&&subjectSelect.value!==topicId)setNativeValue(subjectSelect,topicId);if(!updateReadingProgress(topicId,selectedReading.number,status)){setBlocked(true);return;}const focusInput=form.querySelector('input[data-reading-focus-input="true"]');const statusLabel=status==='completed'?'Completed':'Incomplete';setNativeValue(focusInput,`Reading ${String(selectedReading.number).padStart(2,'0')} — ${selectedReading.title} — ${statusLabel}`);form.dataset.readingDialogBypass='true';setOpen(false);form.requestSubmit();};
 const selectReading=nextNumber=>{setReadingNumber(nextNumber);loadReadingState(topicId,nextNumber);};
 return createPortal(<div className="modalBackdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><div className="modal readingLogModal" role="dialog" aria-modal="true" aria-labelledby="reading-dialog-title"><div className="readingDialogHead"><div><span className="sectionLabel">STUDY SESSION</span><h2 id="reading-dialog-title">Which reading did you study?</h2><p>{topicName} · Select the reading and whether you completed it in this session.</p></div><button type="button" className="modalClose" aria-label="Close" onClick={close}>×</button></div><div className="readingDialogFields"><label>Subject<select value={topicId} onChange={e=>{const nextTopic=e.target.value;const nextReadings=getTopicReadings(nextTopic);setTopicId(nextTopic);setReadingNumber(nextReadings[0]?.number||1);loadReadingState(nextTopic,nextReadings[0]?.number||1);}}>{Object.entries(TOPICS).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Reading<select value={selectedReading?.number||''} onChange={e=>selectReading(Number(e.target.value))}>{readings.map(reading=><option value={reading.number} key={reading.number}>Reading {String(reading.number).padStart(2,'0')} — {reading.title}</option>)}</select></label></div><div className="readingStatusGroup" role="group" aria-label="Reading completion status"><span className="readingStatusLabel">Reading status</span><div className="readingStatusOptions"><button type="button" className={status==='completed'?'selected':''} onClick={()=>setStatus('completed')}>Completed</button><button type="button" className={`${status==='incomplete'?'selected':''} ${incompleteCount>=2?'disabled':''}`} disabled={incompleteCount>=2} onClick={()=>setStatus('incomplete')}>Incomplete</button></div>{incompleteCount===1&&status==='incomplete'?<p className="readingStatusHint">First incomplete attempt: 50% credit. One more incomplete attempt will split the 50% into 25% + 25%.</p>:null}{incompleteCount>=2&&status!=='completed'?<p className="readingStatusHint warning">Two incomplete attempts used. A third incomplete attempt is not allowed. Mark the reading completed when finished.</p>:null}</div><div className="readingDialogPreview"><span>Selected</span><strong>Reading {String(selectedReading?.number||0).padStart(2,'0')}</strong><p>{selectedReading?.title||'No reading selected'}</p><small>{status==='completed'?'100% credit':incompleteCount>=2?'25% + 25% = 50% credit':'50% credit on first incomplete'}</small></div><div className="modalActions"><button className="ghost" type="button" onClick={close}>Cancel</button><button className="primary" type="button" onClick={confirm} disabled={!selectedReading||blocked}>Add study session</button></div></div></div>,document.body);
}
