'use client';

import { createPortal } from 'react-dom';
import { useEffect, useMemo, useState } from 'react';
import { curriculumReadings, readingRanges } from '../lib/curriculumReadings';

const STORE='cfa-l1-tracker-v10';
const TOPICS={quantitativeMethods:'Quantitative Methods',financialStatementAnalysis:'Financial Statement Analysis',fixedIncome:'Fixed Income',corporateFinance:'Corporate Finance',equities:'Equities',economics:'Economics',portfolioConstruction:'Portfolio Construction',derivativesAndRiskManagement:'Derivatives and Risk Management',alternativeInvestments:'Alternative Investments',ethics:'Ethical and Professional Standards'};
const getTopicReadings=id=>{const [start]=readingRanges[id]||[1];return(curriculumReadings[id]||[]).map((title,index)=>({number:start+index,title}));};
const readState=()=>{try{const raw=window.localStorage.getItem(STORE);return raw?JSON.parse(raw):{};}catch{return {};}};
const getReadingProgress=(topicId,number)=>{const item=readState().readingProgress?.[topicId]?.[number];return item&&typeof item==='object'?item:null;};
const saveReadingAttempt=(topicId,number,status)=>{try{const state=readState();const rp=state.readingProgress&&typeof state.readingProgress==='object'?{...state.readingProgress}:{};const tp=rp[topicId]&&typeof rp[topicId]==='object'?{...rp[topicId]}:{};const prev=tp[number]&&typeof tp[number]==='object'?tp[number]:{};const count=Number(prev.incompleteCount)||0;if(status==='incomplete'&&count>=2)return false;const nextCount=status==='incomplete'?count+1:count;let history=Array.isArray(prev.history)?[...prev.history]:[];if(status==='completed')history.push({status:'completed',credit:1,at:new Date().toISOString()});else if(nextCount===1)history.push({status:'incomplete',credit:.5,at:new Date().toISOString()});else{let last=-1;history.forEach((x,i)=>{if(x?.status==='incomplete')last=i;});if(last>=0)history=history.map((x,i)=>i===last?{...x,credit:.25}:x);history.push({status:'incomplete',credit:.25,at:new Date().toISOString()});}tp[number]={status,incompleteCount:nextCount,credit:status==='completed'?1:.5,history};rp[topicId]=tp;const rd={...(state.readingDone&&typeof state.readingDone==='object'?state.readingDone:{})};const done=new Set(Array.isArray(rd[topicId])?rd[topicId]:[]);if(status==='completed')done.add(number);else done.delete(number);rd[topicId]=[...done].sort((a,b)=>a-b);const total=(curriculumReadings[topicId]||[]).length;const topics=new Set(Array.isArray(state.readDone)?state.readDone:[]);if(total&&done.size===total)topics.add(topicId);else topics.delete(topicId);window.localStorage.setItem(STORE,JSON.stringify({...state,readDone:[...topics],readingDone:rd,readingProgress:rp}));window.dispatchEvent(new CustomEvent('cfa-reading-progress-change',{detail:{topicId,number,status}}));return true;}catch{return false;}};
const saveSession=(form,topicId,reading,status)=>{try{const date=form?.querySelector('input[type="date"]')?.value||'';const hours=Number(form?.querySelector('input[type="number"]')?.value);if(!date||!Number.isFinite(hours)||hours<=0||!reading)return false;const state=readState();const logs=Array.isArray(state.logs)?[...state.logs]:[];logs.unshift({id:`${Date.now()}-${Math.random()}`,date,hours,topic:topicId,focus:`Reading ${String(reading.number).padStart(2,'0')} — ${reading.title} — ${status==='completed'?'Completed':'Incomplete'}`,readingNumber:reading.number,readingTitle:reading.title,readingStatus:status});window.localStorage.setItem(STORE,JSON.stringify({...state,logs}));return true;}catch{return false;}};

export default function StudyLogReadingDialog(){
 const [open,setOpen]=useState(false),[form,setForm]=useState(null),[topicId,setTopicId]=useState('quantitativeMethods'),[readingNumber,setReadingNumber]=useState(1),[status,setStatus]=useState('completed'),[error,setError]=useState('');
 const readings=useMemo(()=>getTopicReadings(topicId),[topicId]);const selectedReading=readings.find(r=>r.number===readingNumber)||readings[0];
 const syncFor=(id,num)=>{const item=getReadingProgress(id,num);setStatus(item?.status==='completed'?'completed':'incomplete');setError('');};
 const openDialog=target=>{const select=target.querySelector('select');const id=select?.value||'quantitativeMethods';const rs=getTopicReadings(id);const num=rs[0]?.number||1;setForm(target);setTopicId(id);setReadingNumber(num);syncFor(id,num);setOpen(true);};
 useEffect(()=>{let targetForm=null;let addButton=null;let trigger=null;const attach=()=>{const f=document.querySelector('.logForm');if(!f||f===targetForm)return;if(addButton)addButton.removeEventListener('click',addButton._open);targetForm=f;addButton=f.querySelector('button[type="submit"]');if(addButton){addButton.type='button';const handler=e=>{e.preventDefault();openDialog(f);};addButton._open=handler;addButton.addEventListener('click',handler);}const wide=f.querySelector('.wide');const input=wide?.querySelector('input');if(wide&&input){Array.from(wide.childNodes).forEach(n=>{if(n.nodeType===Node.TEXT_NODE)n.textContent='';});input.style.display='none';input.tabIndex=-1;input.setAttribute('aria-hidden','true');trigger=wide.querySelector('.readingDialogTrigger');if(!trigger){trigger=document.createElement('button');trigger.type='button';trigger.className='readingDialogTrigger';trigger.textContent='Choose a reading…';trigger.addEventListener('click',()=>openDialog(f));wide.appendChild(trigger);}}};attach();const observer=new MutationObserver(attach);observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();if(addButton)addButton.removeEventListener('click',addButton._open);};},[]);
 useEffect(()=>{if(!readings.some(r=>r.number===readingNumber))setReadingNumber(readings[0]?.number||1);},[readings,readingNumber]);
 if(!open||!form||typeof document==='undefined')return null;
 const current=getReadingProgress(topicId,selectedReading?.number||0);const count=Number(current?.incompleteCount)||0;const close=()=>{setOpen(false);setError('');};
 const confirm=()=>{if(!selectedReading)return;if(status==='incomplete'&&count>=2){setError('A third incomplete attempt is not allowed.');return;}if(!saveReadingAttempt(topicId,selectedReading.number,status)){setError('Could not save the reading status.');return;}if(!saveSession(form,topicId,selectedReading,status)){setError('Could not save the study session. Check the date and hours.');return;}close();window.dispatchEvent(new CustomEvent('cfa-study-log-added',{detail:{topicId,readingNumber:selectedReading.number,status}}));window.location.reload();};
 const changeTopic=id=>{const rs=getTopicReadings(id);const num=rs[0]?.number||1;setTopicId(id);setReadingNumber(num);syncFor(id,num);};
 const changeReading=num=>{setReadingNumber(num);syncFor(topicId,num);};
 return createPortal(<div className="modalBackdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><div className="modal readingLogModal" role="dialog" aria-modal="true" aria-labelledby="reading-dialog-title"><div className="readingDialogHead"><div><span className="sectionLabel">STUDY SESSION</span><h2 id="reading-dialog-title">Which reading did you study?</h2><p>{TOPICS[topicId]} · Select the reading and whether you completed it in this session.</p></div><button type="button" className="modalClose" aria-label="Close" onClick={close}>×</button></div><div className="readingDialogFields"><label>Subject<select value={topicId} onChange={e=>changeTopic(e.target.value)}>{Object.entries(TOPICS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Reading<select value={selectedReading?.number||''} onChange={e=>changeReading(Number(e.target.value))}>{readings.map(r=><option key={r.number} value={r.number}>Reading {String(r.number).padStart(2,'0')} — {r.title}</option>)}</select></label></div><div className="readingStatusGroup" role="group" aria-label="Reading completion status"><span className="readingStatusLabel">Reading status</span><div className="readingStatusOptions"><button type="button" className={status==='completed'?'selected':''} onClick={()=>{setStatus('completed');setError('');}}>Completed</button><button type="button" className={`${status==='incomplete'?'selected':''} ${count>=2?'disabled':''}`} disabled={count>=2} onClick={()=>{setStatus('incomplete');setError('');}}>Incomplete</button></div>{count===1&&status==='incomplete'?<p className="readingStatusHint">First incomplete attempt: 50% credit. A second incomplete attempt splits this into 25% + 25%.</p>:null}{count>=2&&status!=='completed'?<p className="readingStatusHint warning">Two incomplete attempts used. A third incomplete attempt is not allowed.</p>:null}{error?<p className="readingStatusHint warning">{error}</p>:null}</div><div className="readingDialogPreview"><span>Selected</span><strong>Reading {String(selectedReading?.number||0).padStart(2,'0')}</strong><p>{selectedReading?.title||'No reading selected'}</p></div><div className="modalActions"><button className="ghost" type="button" onClick={close}>Cancel</button><button className="primary" type="button" onClick={confirm} disabled={!selectedReading||!!(count>=2&&status==='incomplete')}>Save study session</button></div></div></div>,document.body);
}
