'use client';

import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { curriculumReadings, readingRanges } from '../lib/curriculumReadings';

const STORE='cfa-l1-tracker-v10';
const TOPIC_IDS={'Quantitative Methods':'quantitativeMethods','Economics':'economics','Corporate Finance':'corporateFinance','Financial Statement Analysis':'financialStatementAnalysis','Equities':'equities','Fixed Income':'fixedIncome','Derivatives and Risk Management':'derivativesAndRiskManagement','Derivatives':'derivativesAndRiskManagement','Alternative Investments':'alternativeInvestments','Portfolio Construction':'portfolioConstruction','Ethics':'ethics','Ethical and Professional Standards':'ethics'};
const TOPIC_HOURS={quantitativeMethods:32,financialStatementAnalysis:52,fixedIncome:46,corporateFinance:26,equities:44,economics:32,portfolioConstruction:32,derivativesAndRiskManagement:26,alternativeInvestments:22,ethics:48};

function getReadings(topicId){const [start]=readingRanges[topicId]||[1];return(curriculumReadings[topicId]||[]).map((title,index)=>({number:start+index,title}));}
function readProgress(){try{const raw=window.localStorage.getItem(STORE);const state=raw?JSON.parse(raw):{};return{readDone:Array.isArray(state.readDone)?state.readDone:[],readingDone:state.readingDone&&typeof state.readingDone==='object'?state.readingDone:{},readingProgress:state.readingProgress&&typeof state.readingProgress==='object'?state.readingProgress:{}};}catch{return{readDone:[],readingDone:{},readingProgress:{}}}}
function getReadingState(topicId,number){const state=readProgress();const completed=Array.isArray(state.readingDone?.[topicId])&&state.readingDone[topicId].includes(number);const item=state.readingProgress?.[topicId]?.[number];if(completed)return{status:'completed',credit:1,incompleteCount:Number(item?.incompleteCount)||0};const count=Number(item?.incompleteCount)||0;return{status:count>0?'incomplete':'open',credit:count>0?0.5:0,incompleteCount:count};}

function setReadingCompleted(topicId,number,readings,completed){try{const state=readProgress();const readingDone={...state.readingDone};const current=new Set(Array.isArray(readingDone[topicId])?readingDone[topicId]:[]);const readingProgress={...state.readingProgress,[topicId]:{...(state.readingProgress?.[topicId]||{})}};const existing=readingProgress[topicId]?.[number]||{};
 if(completed){current.add(number);readingProgress[topicId][number]={...existing,status:'completed',credit:1,history:[...(existing.history||[]),{status:'completed',credit:1,at:new Date().toISOString()}]};}
 else{current.delete(number);readingProgress[topicId][number]={...existing,status:'open',credit:0};}
 readingDone[topicId]=[...current].sort((a,b)=>a-b);const topics=new Set(state.readDone||[]);if(readings.length&&current.size===readings.length)topics.add(topicId);else topics.delete(topicId);
 window.localStorage.setItem(STORE,JSON.stringify({...state,readDone:[...topics],readingDone,readingProgress}));window.dispatchEvent(new CustomEvent('cfa-reading-progress-change',{detail:{topicId,number,status:completed?'completed':'open'}}));}
 catch{}}

function ensureTopicCard(node,topicId,readings){const states=readings.map(r=>getReadingState(topicId,r.number));const completed=states.filter(s=>s.status==='completed').length;const credit=states.reduce((sum,s)=>sum+s.credit,0);const total=readings.length;const percent=total?Math.round(credit/total*100):0;const topicHeader=node.querySelector('.topicTop > div');const topicMeta=topicHeader?.querySelector('.topicMeta')||topicHeader?.querySelector(':scope > span:nth-child(2)');if(topicMeta){topicMeta.classList.add('topicMeta');topicMeta.textContent=`${completed}/${total} modules complete · ${percent}% credit`;}
 const oldHoursBar=node.querySelector(':scope > .bar');if(oldHoursBar)oldHoursBar.style.display='none';const oldFooter=node.querySelector(':scope > .topicFooter');if(oldFooter){const first=oldFooter.querySelector(':scope > span:first-child');if(first)first.style.display='none';}
 let moduleProgress=node.querySelector(':scope > .topicModuleProgress');if(!moduleProgress){moduleProgress=document.createElement('div');moduleProgress.className='topicModuleProgress';moduleProgress.setAttribute('role','progressbar');const track=document.createElement('span');track.className='topicModuleTrack';const fill=document.createElement('span');fill.className='topicModuleFill';track.appendChild(fill);moduleProgress.appendChild(track);const value=document.createElement('span');value.className='topicModuleValue';moduleProgress.appendChild(value);node.insertBefore(moduleProgress,node.querySelector(':scope > .topicActions')||null);}
 const fill=moduleProgress.querySelector('.topicModuleFill');const value=moduleProgress.querySelector('.topicModuleValue');const track=moduleProgress.querySelector('.topicModuleTrack');if(fill)fill.style.width=`${percent}%`;if(value)value.textContent=`${completed}/${total} complete · ${percent}% credit`;moduleProgress.setAttribute('aria-valuemin','0');moduleProgress.setAttribute('aria-valuemax',String(total));moduleProgress.setAttribute('aria-valuenow',String(credit));moduleProgress.setAttribute('aria-valuetext',`${completed} of ${total} learning modules complete; ${percent}% credit`);if(track)track.setAttribute('aria-hidden','true');const status=node.querySelector(':scope > .topicTop > .status');if(status){status.classList.add('topicStatusBadge');status.textContent=completed===total?'TOPIC COMPLETE':'IN PROGRESS';}}

function ReadingPanel({title,topicId,readings}){const [tick,setTick]=useState(0);void tick;const plannedHours=TOPIC_HOURS[topicId]||0;const hoursPerReading=roundToHalf(readings.length?plannedHours/readings.length:0);const states=readings.map(r=>({...r,...getReadingState(topicId,r.number)}));const completedCount=states.filter(r=>r.status==='completed').length;const credit=states.reduce((sum,r)=>sum+r.credit,0);const percent=readings.length?Math.round(credit/readings.length*100):0;const coveredHours=credit*hoursPerReading;
 useEffect(()=>{const onChange=e=>{if(e.detail?.topicId===topicId)setTick(x=>x+1);};window.addEventListener('cfa-reading-progress-change',onChange);return()=>window.removeEventListener('cfa-reading-progress-change',onChange);},[topicId]);
 return <div className="topicReadings"><div className="topicReadingsSummary"><div className="topicReadingsSummaryMain"><span className="topicReadingsLabel">READING TRACKER</span><strong>{completedCount} / {readings.length} complete · {percent}% credit</strong></div><span className="topicReadingsPercent">{percent}%</span></div><div className="topicReadingProgressMeta" aria-label={`${completedCount} of ${readings.length} readings complete. ${percent}% credit. ${coveredHours.toFixed(1)} of ${plannedHours} planned hours covered.`}><span className="topicReadingProgressTrack"><span style={{width:`${percent}%`}}/></span><span className="topicReadingProgressTime">{coveredHours.toFixed(1)}h / {plannedHours}h planned</span></div><div className="topicReadingsBody"><div className="topicReadingsHead"><span>{title} · READINGS</span><span>{hoursPerReading.toFixed(1)}h est. / reading</span></div><ol className="topicReadingsList">{states.map(reading=>{const done=reading.status==='completed';const partial=!done&&reading.credit>0;const locked=reading.incompleteCount>=2&&!done;const label=done?'Completed':locked?'2 incomplete attempts · 50% credit':partial?(reading.incompleteCount===1?'Incomplete · 50% credit':'Incomplete · 25% + 25% credit'):'Open';return <li key={reading.number} className={`${done?'isComplete ':''}${partial?'isPartial ':''}${locked?'isLockedIncomplete':''}`}><label className="topicReadingCheck"><input type="checkbox" checked={done} onChange={e=>{if(locked&& !done)return;setReadingCompleted(topicId,reading.number,readings,e.target.checked);}} disabled={locked&& !done} aria-label={`Reading ${String(reading.number).padStart(2,'0')}: ${reading.title}. ${label}`}/><span className="topicReadingCheckBox" aria-hidden="true"/><span className="topicReadingNumber">Reading {String(reading.number).padStart(2,'0')}</span><span className="topicReadingTitle">{reading.title}</span><span className="topicReadingStatus">{label}</span><span className="topicReadingHours">{hoursPerReading.toFixed(1)}h</span></label></li>;})}</ol></div></div>}
function roundToHalf(value){return Math.round(value*2)/2;}

export default function TopicReadingsEnhancer(){const [targets,setTargets]=useState([]);
 useEffect(()=>{let lastSignature=null;let scheduled=false;const scan=()=>{scheduled=false;const nodes=Array.from(document.querySelectorAll('.topicGrid .topic'));const items=nodes.map(node=>{const title=node.querySelector('.topicTitle')?.textContent?.trim()||'';return{node,title,topicId:TOPIC_IDS[title]};}).filter(item=>item.topicId);const signature=items.map(item=>`${item.topicId}:${item.title}`).join('|');if(signature===lastSignature)return;lastSignature=signature;if(!items.length){setTargets([]);return;}const next=items.map(({node,title,topicId})=>{let target=node.querySelector(':scope > .topicReadingsMount');if(!target){target=document.createElement('div');target.className='topicReadingsMount';node.appendChild(target);}const readings=getReadings(topicId);node.setAttribute('data-topic-id',topicId);ensureTopicCard(node,topicId,readings);return{target,title,topicId};});setTargets(next);};const requestScan=()=>{if(scheduled)return;scheduled=true;window.requestAnimationFrame(scan);};requestScan();const observer=new MutationObserver(requestScan);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect();},[]);
 useEffect(()=>{const onChange=e=>{const id=e.detail?.topicId;if(!id)return;const item=document.querySelector(`.topicGrid .topic[data-topic-id="${id}"]`);if(item)ensureTopicCard(item,id,getReadings(id));};window.addEventListener('cfa-reading-progress-change',onChange);return()=>window.removeEventListener('cfa-reading-progress-change',onChange);},[]);
 useEffect(()=>{const onReset=event=>{const button=event.target?.closest?.('button');if(!button)return;const text=button.textContent?.trim().toLowerCase()||'';if(text!=='reset study data')return;window.setTimeout(()=>{try{const raw=window.localStorage.getItem(STORE);const state=raw?JSON.parse(raw):{};window.localStorage.setItem(STORE,JSON.stringify({...state,readDone:[],readingDone:{},readingProgress:{}}));window.dispatchEvent(new CustomEvent('cfa-reading-progress-change',{detail:{reset:true}}));}catch{}},0);};document.addEventListener('click',onReset);return()=>document.removeEventListener('click',onReset);},[]);
 return <>{targets.map(({target,title,topicId})=>createPortal(<ReadingPanel key={`${topicId}-${title}`} title={title} topicId={topicId} readings={getReadings(topicId)}/>,target))}</>;}
