'use client';
import {useEffect,useMemo,useState} from 'react';

const readings=[['quant','Quant Methods','Sep 1–21',32],['fsa1','FSA Part 1','Sep 22–Oct 12',26],['fsa2','FSA Part 2','Oct 13–27',26],['fi1','Fixed Income 1','Oct 28–Nov 10',23],['fi2','Fixed Income 2','Nov 11–24',23],['ci','Corporate Issuers','Nov 25–Dec 15',26],['equity','Equity','Dec 16–Jan 12',44],['econ','Economics','Jan 13–Feb 2',32],['pm','Portfolio Management','Feb 3–23',32],['deriv','Derivatives','Feb 24–Mar 9',26],['alts','Alternatives','Mar 10–23',22],['ethics','Ethics','Mar 24–Apr 7',48]];
const revisions=[['r1','Apr 16–30','High Weight','FSA, Equity and Ethics'],['r2','May 1–15','Core Focus','Fixed Income, Quant and Corporate Issuers'],['r3','May 16–31','Applied','Economics, Derivatives, PM and Alternatives'],['r4','Jun 1–15','Mixed Practice','Full mixed sets and weak-area review']];
const dates=['2027-06-16','2027-06-21','2027-06-26','2027-07-01','2027-07-06','2027-07-11','2027-07-16','2027-07-21','2027-07-26','2027-08-01','2027-08-05','2027-08-10'];
const freshMocks=()=>dates.map((date,i)=>({id:i+1,date,score:'',done:false,completedAt:''}));
const STORE='cfa-l1-tracker-v9';
const iso=()=>new Date().toISOString().slice(0,10);
const parse=v=>new Date(`${String(v)}T12:00:00`);
const fmt=v=>{const d=parse(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})};
const weekStart=v=>{const d=new Date(v),n=d.getDay();d.setDate(d.getDate()-(n===0?6:n-1));d.setHours(0,0,0,0);return d};
const phaseFor=v=>v<new Date('2027-04-16')?['Phase 1 · First Pass',9]:v<new Date('2027-06-16')?['Phase 2 · Revision',15]:v<new Date('2027-08-11')?['Phase 3 · 12-Mock Gauntlet',18]:['Final Polish & Rest',8];
const cleanMocks=v=>{const d=freshMocks();return Array.isArray(v)?d.map((x,i)=>{const m=v[i];return m&&typeof m==='object'?{...x,date:typeof m.date==='string'?m.date:x.date,score:m.score==null?'':String(m.score),done:!!m.done,completedAt:typeof m.completedAt==='string'?m.completedAt:''}:x}):d};
const cleanLogs=v=>Array.isArray(v)?v.filter(x=>x&&typeof x==='object').map((x,i)=>({id:x.id??`${Date.now()}-${i}`,date:typeof x.date==='string'?x.date:iso(),hours:Number(x.hours)||0,topic:readings.some(r=>r[0]===x.topic)?x.topic:'quant',focus:typeof x.focus==='string'?x.focus:''})).filter(x=>x.hours>0):[];

export default function Home(){
 const [tab,setTab]=useState('Dashboard'),[readDone,setReadDone]=useState([]),[revDone,setRevDone]=useState([]),[mocks,setMocks]=useState(freshMocks),[logs,setLogs]=useState([]),[rest,setRest]=useState([]),[logDate,setLogDate]=useState(iso()),[logHours,setLogHours]=useState(''),[logTopic,setLogTopic]=useState('quant'),[logFocus,setLogFocus]=useState(''),[dialog,setDialog]=useState(null),[score,setScore]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{try{const s=JSON.parse(window.localStorage.getItem(STORE)||'{}');setReadDone(Array.isArray(s.readDone)?s.readDone.filter(id=>readings.some(r=>r[0]===id)):[]);setRevDone(Array.isArray(s.revDone)?s.revDone.filter(id=>revisions.some(r=>r[0]===id)):[]);setMocks(cleanMocks(s.mocks));setLogs(cleanLogs(s.logs));setRest(Array.isArray(s.rest)?s.rest.filter(x=>typeof x==='string'):[])}catch{setReadDone([]);setRevDone([]);setMocks(freshMocks());setLogs([]);setRest([])}setReady(true)},[]);
 useEffect(()=>{if(ready)try{window.localStorage.setItem(STORE,JSON.stringify({readDone,revDone,mocks,logs,rest}))}catch{}},[readDone,revDone,mocks,logs,rest,ready]);
 const today=new Date(),exam=new Date('2027-08-15T00:00:00'),days=Math.max(0,Math.ceil((exam-today)/86400000)),phase=phaseFor(today);
 const readingPct=Math.round(readDone.length/12*100),revisionPct=Math.round(revDone.length/4*100),mockDone=mocks.filter(Boolean).filter(m=>m.done).length,mockPct=Math.round(mockDone/12*100);
 const weighted={first:readDone.length/12*50,revision:revDone.length/4*20,mocks:mockDone/12*30,total:readDone.length/12*50+revDone.length/4*20+mockDone/12*30};
 const studyHours=logs.reduce((s,x)=>s+Number(x?.hours||0),0),ws=weekStart(today),we=new Date(ws);we.setDate(we.getDate()+7);const weekHours=logs.filter(x=>{const d=parse(x.date);return d>=ws&&d<we}).reduce((s,x)=>s+Number(x?.hours||0),0);
 const streak=(()=>{let n=0,d=new Date();d.setHours(12,0,0,0);for(let i=0;i<365;i++){const k=d.toISOString().slice(0,10),active=logs.some(x=>x?.date===k&&Number(x?.hours)>0);if(!active&&!rest.includes(k))break;if(active)n++;d.setDate(d.getDate()-1)}return n})();
 const topics=useMemo(()=>readings.map(r=>{const l=logs.filter(x=>x?.topic===r[0]);return{...r,logged:l.reduce((s,x)=>s+Number(x?.hours||0),0),sessions:l.length}}),[logs]);
 const next=readings.find(r=>!readDone.includes(r[0]))||readings[11];
 const weekDays=Array.from({length:7},(_,i)=>{const d=new Date(ws);d.setDate(d.getDate()+i);const k=d.toISOString().slice(0,10);return{k,d,hours:logs.filter(x=>x?.date===k).reduce((s,x)=>s+Number(x?.hours||0),0),rest:rest.includes(k)}});
 const trend=useMemo(()=>mocks.filter(m=>m?.done&&m.completedAt&&Number.isFinite(Number(m.score))).slice().sort((a,b)=>parse(a.completedAt)-parse(b.completedAt)||a.id-b.id),[mocks]);
 const average=trend.length?Math.round(trend.reduce((s,m)=>s+Number(m.score),0)/trend.length):null;
 const chart={w:920,h:300,l:56,r:24,t:18,b:66},cx=i=>trend.length<2?chart.w/2:chart.l+i*(chart.w-chart.l-chart.r)/(trend.length-1),cy=s=>chart.t+(100-s)*(chart.h-chart.t-chart.b)/100,path=trend.map((m,i)=>`${i?'L':'M'} ${cx(i)} ${cy(Number(m.score))}`).join(' ');
 const addLog=e=>{e.preventDefault();const h=Number(logHours);if(!logDate||!Number.isFinite(h)||h<=0)return;setLogs(x=>[{id:`${Date.now()}-${Math.random()}`,date:logDate,hours:h,topic:logTopic,focus:logFocus.trim()},...x]);setLogHours('');setLogFocus('')};
 const deleteLog=id=>setLogs(x=>x.filter(y=>y?.id!==id));
 const toggleRest=k=>setRest(x=>x.includes(k)?x.filter(v=>v!==k):[...x,k]);
 const toggleRead=id=>setReadDone(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const toggleRev=id=>setRevDone(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const toggleMock=id=>{const m=mocks.find(x=>x.id===id);if(!m)return;if(m.done){setMocks(x=>x.map(y=>y.id===id?{...y,done:false,completedAt:''}:y));return}setScore(m.score||'');setDialog(id)};
 const completeMock=()=>{const n=Number(score);if(dialog===null||!Number.isFinite(n)||n<0||n>100)return;setMocks(x=>x.map(m=>m.id===dialog?{...m,score:String(n),done:true,completedAt:iso()}:m));setDialog(null);setScore('')};
 const resetStudy=()=>{if(window.confirm('Reset study data? This clears study sessions, first-pass reading completion, revision completion and rest days.')){setLogs([]);setReadDone([]);setRevDone([]);setRest([])}};
 const resetMocks=()=>{if(window.confirm('Reset mock data? This clears all mock scores, completion states and completion dates.'))setMocks(freshMocks())};
 return <main className="shell">
  <header className="topbar"><div><div className="eyebrow">CFA LEVEL I · AUGUST 2027</div><h1>Study Tracker</h1><p>Plan, execute and measure the roadmap in one place.</p></div><div className="count"><strong>{days}</strong><span>days to exam</span></div></header>
  <nav className="nav">{['Dashboard','Roadmap','Topics','Study Log','Mocks'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>
  {tab==='Dashboard'&&<>
   <section className="hero"><div><span className="pill">{phase[0]}</span><h2>Track what actually earns progress.</h2><p>Completion and readiness are shown separately so every number has a clear meaning.</p><div className="heroSummary"><span><i className="legendDot first"/>First Pass <b>{weighted.first.toFixed(1)}%</b><small>earned / 50%</small></span><span><i className="legendDot rev"/>Revision <b>{weighted.revision.toFixed(1)}%</b><small>earned / 20%</small></span><span><i className="legendDot mock"/>Mocks <b>{weighted.mocks.toFixed(1)}%</b><small>earned / 30%</small></span></div></div><div className="readinessWrap"><div className="weightedRing" style={{'--first':`${weighted.first}%`,'--revEnd':`${weighted.first+weighted.revision}%`,'--total':`${weighted.total}%`}}><div><b>{Math.round(weighted.total)}%</b><span>readiness</span></div></div><div className="ringCaption">100% = exam readiness</div></div></section>
   <section className="readinessBreakdown"><div className="breakHead"><div><span className="sectionLabel">READINESS BREAKDOWN</span><h3>Every completed unit moves the total</h3></div><strong>{Math.round(weighted.total)} / 100</strong></div><SegmentBar count={12} done={readDone.length} label="First Pass" weight="50%" color="first"/><SegmentBar count={4} done={revDone.length} label="Revision" weight="20%" color="rev"/><SegmentBar count={12} done={mockDone} label="Mocks" weight="30%" color="mock"/></section>
   <div className="grid four"><KpiCard label="Overall readiness" value={`${Math.round(weighted.total)}%`} sub="Actual readiness earned" tone="blue"/><KpiCard label="First Pass" value={`${readDone.length}/12`} sub={`${readingPct}% complete · ${weighted.first.toFixed(1)}% earned`} tone="cyan"/><KpiCard label="Revision" value={`${revDone.length}/4`} sub={`${revisionPct}% complete · ${weighted.revision.toFixed(1)}% earned`} tone="purple"/><KpiCard label="Mocks" value={`${mockDone}/12`} sub={`${mockPct}% complete · ${weighted.mocks.toFixed(1)}% earned`} tone="orange"/></div>
   <div className="dashboardGrid"><section className="panel"><div className="panelHead"><div><span className="sectionLabel">EXECUTION</span><h3>This week</h3><p>{weekHours}h logged · {phase[1]}h target · {streak} day streak</p></div></div><div className="weekGrid">{weekDays.map(x=><div className={`dayCell ${x.rest?'rest':''}`} key={x.k}><span>{x.d.toLocaleDateString('en-IN',{weekday:'short'})}</span><strong>{x.hours?`${x.hours}h`:'—'}</strong><small>{x.rest?'Rest':x.hours?'Studied':'Open'}</small></div>)}</div></section><section className="panel"><div className="panelHead"><div><span className="sectionLabel">NEXT READING</span><h3>{next[1]}</h3><p>{next[3]}h planned · {next[2]}</p></div><button className="primary" onClick={()=>{setLogTopic(next[0]);setTab('Study Log')}}>Log session</button></div><div className={`nextState ${readDone.includes(next[0])?'complete':''}`}><span className="statusDot"/> {readDone.includes(next[0])?'Reading complete':'Reading open'} <b>{readDone.includes(next[0])?'4.17% earned':'4.17% available'}</b></div></section></div>
   <section className="panel"><div className="panelHead"><div><span className="sectionLabel">MOCK READINESS · 30%</span><h3>Score trend</h3><p>{trend.length?'Actual completion dates are plotted below.':'Complete mocks to build the dated line chart.'}</p></div><button className="primary" onClick={()=>setTab('Mocks')}>Open mocks</button></div>{trend.length?<LineChart points={trend} chart={chart} cx={cx} cy={cy} path={path}/>:<div className="chartEmpty">No completed mock scores yet.</div>}</section>
  </>}
  {tab==='Roadmap'&&<section className="panel"><div className="panelHead"><div><span className="sectionLabel">WEIGHTED ROADMAP</span><h2>First Pass + Revision</h2><p>Click a unit when it is genuinely complete. Each check has an explicit contribution.</p></div><span className="pill">{Math.round(weighted.first+weighted.revision)}% earned</span></div><div className="phaseBanner first"><div><strong>FIRST PASS</strong><span>50% of readiness · {readDone.length}/12 complete</span></div><b>{weighted.first.toFixed(1)}%</b></div>{readings.map(r=>{const d=readDone.includes(r[0]);return <div className={`road ${d?'isDone':''}`} key={r[0]}><button className={`check ${d?'done':''}`} onClick={()=>toggleRead(r[0])}>{d?'✓':''}</button><div className="roadDate">{r[2]}</div><div className="roadMain"><strong>{r[1]}</strong><span>{d?'Completed reading':'Reading completion target'}</span></div><div className="roadHours"><b>{d?'Complete':'Open'}</b><small>+{(50/12).toFixed(2)}% readiness</small></div></div>})}<div className="subsection"><div className="phaseBanner rev"><div><strong>REVISION</strong><span>20% of readiness · {revDone.length}/4 complete</span></div><b>{weighted.revision.toFixed(1)}%</b></div>{revisions.map(r=>{const d=revDone.includes(r[0]);return <div className={`revision ${d?'isDone':''}`} key={r[0]}><button className={`check ${d?'done':''}`} onClick={()=>toggleRev(r[0])}>{d?'✓':''}</button><div><strong>{r[1]}</strong><span>{r[2]}</span></div><p>{r[3]}</p><b>{d?'5.0% earned':'5.0% available'}</b></div>})}</div></section>}
  {tab==='Topics'&&<section className="panel"><div className="panelHead"><div><span className="sectionLabel">TOPICS</span><h2>Topic execution</h2><p>Study Log hours feed these progress bars. Reading completion separately controls First Pass readiness.</p></div><button className="ghost" onClick={resetStudy}>Reset study data</button></div><div className="topicGrid">{topics.map(r=>{const d=readDone.includes(r[0]),hp=Math.min(100,Math.round(r.logged/r[3]*100));return <div className={`topic ${d?'topicDone':''}`} key={r[0]}><div className="topicTop"><div><strong>{r[1]}</strong><span>{r.logged}h / {r[3]}h planned · {r.sessions} sessions</span></div><span className={`status ${d?'doneText':''}`}>{d?'READING DONE':'READING OPEN'}</span></div><div className="bar"><i style={{width:`${hp}%`}}/></div><div className="topicFooter"><span>{hp}% hours logged</span><b>{d?'+4.17% readiness earned':'+4.17% available'}</b></div><div className="topicActions"><button onClick={()=>{setLogTopic(r[0]);setTab('Study Log')}}>Log session</button><button onClick={()=>toggleRead(r[0])}>{d?'Undo reading':'Mark reading complete'}</button></div></div>})}</div></section>}
  {tab==='Study Log'&&<section className="panel"><div className="panelHead"><div><span className="sectionLabel">EXECUTION LOG</span><h2>Study Log</h2><p>Logging hours improves execution tracking; checking a reading/revision unit changes weighted readiness.</p></div><button className="ghost" onClick={resetStudy}>Reset study data</button></div><div className="logNotice"><span className="noticeIcon">i</span><div><strong>Two different progress signals</strong><p><b>Hours logged</b> = execution. <b>Completion checks</b> = weighted readiness. This keeps the tracker honest instead of turning raw hours into automatic readiness.</p></div></div><form className="logForm" onSubmit={addLog}><label>Date<input type="date" value={logDate} onChange={e=>setLogDate(e.target.value)}/></label><label>Hours<input type="number" min="0.25" step="0.25" value={logHours} onChange={e=>setLogHours(e.target.value)} placeholder="2.5"/></label><label>Topic<select value={logTopic} onChange={e=>setLogTopic(e.target.value)}>{readings.map(r=><option value={r[0]} key={r[0]}>{r[1]}</option>)}</select></label><label className="wide">Focus / notes<input value={logFocus} onChange={e=>setLogFocus(e.target.value)} placeholder="TVM practice, questions, review…"/></label><button className="primary" type="submit">Add session</button></form><div className="weekStats"><div><strong>{studyHours}h</strong><span>Total study</span></div><div><strong>{weekHours}h</strong><span>This week</span></div><div><strong>{phase[1]}h</strong><span>Weekly target</span></div><div><strong>{streak}</strong><span>Study streak</span></div></div><div className="dayPlanner">{weekDays.map(x=><div className={`dayPlan ${x.rest?'rest':''}`} key={x.k}><div><strong>{x.d.toLocaleDateString('en-IN',{weekday:'short'})}</strong><span>{x.d.toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</span></div><b>{x.hours}h</b><button type="button" onClick={()=>toggleRest(x.k)}>{x.rest?'Remove rest':'Mark rest'}</button></div>)}</div><div className="logList">{logs.length?logs.map(x=><div className="logRow" key={x.id}><span>{fmt(x.date)}</span><em>{x.hours}h</em><span>{readings.find(r=>r[0]===x.topic)?.[1]||x.topic}</span><span>{x.focus||'—'}</span><button onClick={()=>deleteLog(x.id)} aria-label="Delete study session">×</button></div>):<div className="empty">No study sessions logged yet.</div>}</div></section>}
  {tab==='Mocks'&&<section className="panel"><div className="panelHead"><div><span className="sectionLabel">PHASE 3 · 30%</span><h2>12-Mock Gauntlet</h2><p>Each completed mock contributes exactly 2.5% of overall readiness.</p></div><button className="ghost" onClick={resetMocks}>Reset mock data</button></div><div className="mockGrid">{mocks.map(m=><div className={`mock ${m.done?'mockDone':''}`} key={m.id}><div className="mockTop"><div><span>MOCK {m.id}</span><strong>{fmt(m.date)}</strong></div><button className={`check ${m.done?'done':''}`} onClick={()=>toggleMock(m.id)}>{m.done?'✓':''}</button></div>{m.done?<div className="mockScore"><b>{m.score}%</b><span>Completed {fmt(m.completedAt)} · +2.5% readiness</span></div>:<div className="mockScore"><span>Not completed · +2.5% available</span></div>}<button className="ghost mockAction" onClick={()=>toggleMock(m.id)}>{m.done?'Mark incomplete':'Mark completed'}</button></div>)}</div>{trend.length?<LineChart points={trend} chart={chart} cx={cx} cy={cy} path={path}/>:null}</section>}
  {dialog!==null&&<div className="modalBackdrop" role="dialog" aria-modal="true"><div className="modal"><span className="sectionLabel">COMPLETE MOCK {dialog}</span><h2>Enter mock score</h2><p>The score is required. Today's date will automatically be saved as the completion date.</p><label>Score (%)<input autoFocus type="number" min="0" max="100" value={score} onChange={e=>setScore(e.target.value)} placeholder="e.g. 72"/></label><div className="modalActions"><button className="ghost" onClick={()=>{setDialog(null);setScore('')}}>Cancel</button><button className="primary" disabled={score===''||!Number.isFinite(Number(score))||Number(score)<0||Number(score)>100} onClick={completeMock}>Complete mock</button></div></div></div>}
  <footer><span>Overall readiness = First Pass 50% + Revision 20% + Mocks 30%</span><span>Study data stored in this browser</span></footer>
 </main>;
}

function KpiCard({label,value,sub,tone}){return <article className={`card tone-${tone}`}><span>{label}</span><strong>{value}</strong><small>{sub}</small></article>}
function SegmentBar({count,done,label,weight,color}){return <div className="segmentRow"><div className="segmentLabel"><span><i className={`legendDot ${color}`}/>{label}</span><b>{done}/{count}</b><em>{weight}</em></div><div className="segments">{Array.from({length:count},(_,i)=><i className={`${i<done?'filled':''} ${color}`} key={i}/> )}</div></div>}
function LineChart({points,chart,cx,cy,path}){return <div className="lineChartWrap"><svg className="lineChart" viewBox={`0 0 ${chart.w} ${chart.h}`} role="img" aria-label="Mock score trend">{[0,25,50,75,100].map(v=><g key={v}><line className="gridLine" x1={chart.l} x2={chart.w-chart.r} y1={cy(v)} y2={cy(v)}/><text className="axisText" x={chart.l-12} y={cy(v)+4} textAnchor="end">{v}</text></g>)}{points.length>1&&<path d={path} fill="none" stroke="#67dfcf" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>}{points.map((p,i)=><g key={`${p.id}-${p.completedAt}`}><circle className="chartDot" cx={cx(i)} cy={cy(Number(p.score))} r="5"/><text className="scoreText" x={cx(i)} y={cy(Number(p.score))-11} textAnchor="middle">{p.score}%</text><text className="dateText" x={cx(i)} y={chart.h-28} textAnchor="middle">{fmt(p.completedAt)}</text><text className="dateText" x={cx(i)} y={chart.h-12} textAnchor="middle">Mock {p.id}</text></g>)}</svg></div>}
