'use client';
import {useEffect,useMemo,useState} from 'react';

const topicWeights={
 ethics:12.5,
 quantitativeMethods:12.5,
 economics:7.5,
 financialStatementAnalysis:12.5,
 corporateFinance:7.5,
 equities:12.5,
 fixedIncome:12.5,
 derivativesAndRiskManagement:7.5,
 alternativeInvestments:7.5,
 portfolioConstruction:10
};
const TOTAL_WEIGHT=Object.values(topicWeights).reduce((s,w)=>s+w,0);
const readings=[
 ['quantitativeMethods','Quantitative Methods','Sep 1–21',32,12.5],['financialStatementAnalysis','Financial Statement Analysis','Sep 22–Oct 27',52,12.5],['fixedIncome','Fixed Income','Oct 28–Nov 24',46,12.5],['corporateFinance','Corporate Finance','Nov 25–Dec 15',26,7.5],['equities','Equities','Dec 16–Jan 12',44,12.5],['economics','Economics','Jan 13–Feb 2',32,7.5],['portfolioConstruction','Portfolio Construction','Feb 3–23',32,10],['derivativesAndRiskManagement','Derivatives and Risk Management','Feb 24–Mar 9',26,7.5],['alternativeInvestments','Alternative Investments','Mar 10–23',22,7.5],['ethics','Ethical and Professional Standards','Mar 24–Apr 7',48,12.5]
];
const revisions=[['r1','Apr 16–30','High Weight','Financial Statement Analysis, Equities and Ethical and Professional Standards'],['r2','May 1–15','Core Focus','Fixed Income, Quantitative Methods and Corporate Finance'],['r3','May 16–31','Applied','Economics, Derivatives and Risk Management, Portfolio Construction and Alternative Investments'],['r4','Jun 1–15','Mixed Practice','Full mixed sets and targeted weak-area review']];
const dates=['2027-06-16','2027-06-21','2027-06-26','2027-07-01','2027-07-06','2027-07-11','2027-07-16','2027-07-21','2027-07-26','2027-08-01','2027-08-05','2027-08-10'];
const freshMocks=()=>dates.map((date,i)=>({id:i+1,date,score:'',done:false,completedAt:''}));
const STORE='cfa-l1-tracker-v10';
const LEGACY_STORE='cfa-l1-tracker-v9';
const iso=()=>new Date().toISOString().slice(0,10);
const parse=v=>new Date(`${String(v)}T12:00:00`);
const fmt=v=>{const d=parse(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})};
const weekStart=v=>{const d=new Date(v),n=d.getDay();d.setDate(d.getDate()-(n===0?6:n-1));d.setHours(0,0,0,0);return d};
const phaseFor=v=>v<new Date('2027-04-16')?['Phase 1 · First Pass',9]:v<new Date('2027-06-16')?['Phase 2 · Revision',15]:v<new Date('2027-08-11')?['Phase 3 · 12-Mock Gauntlet',18]:['Final Polish & Rest',8];
const aliases={quant:'quantitativeMethods',fsa1:'financialStatementAnalysis',fsa2:'financialStatementAnalysis',fi1:'fixedIncome',fi2:'fixedIncome',ci:'corporateFinance',equity:'equities',econ:'economics',pm:'portfolioConstruction',deriv:'derivativesAndRiskManagement',alts:'alternativeInvestments',ethics:'ethics'};
const normalizeTopic=id=>aliases[id]||id;
const cleanMocks=v=>{const d=freshMocks();return Array.isArray(v)?d.map((x,i)=>{const m=v[i];return m&&typeof m==='object'?{...x,date:typeof m.date==='string'?m.date:x.date,score:m.score==null?'':String(m.score),done:!!m.done,completedAt:typeof m.completedAt==='string'?m.completedAt:''}:x}):d};
const cleanLogs=v=>Array.isArray(v)?v.filter(x=>x&&typeof x==='object').map((x,i)=>({id:x.id??`${Date.now()}-${i}`,date:typeof x.date==='string'?x.date:iso(),hours:Number(x.hours)||0,topic:normalizeTopic(x.topic),focus:typeof x.focus==='string'?x.focus:''})).filter(x=>x.hours>0):[];
const cleanTopicIds=(v,allowed)=>Array.isArray(v)?[...new Set(v.map(normalizeTopic).filter(id=>allowed.has(id)))]:[];
const migrateState=s=>{const allowed=new Set(readings.map(r=>r[0]));return {readDone:cleanTopicIds(s?.readDone,allowed),revDone:Array.isArray(s?.revDone)?[...new Set(s.revDone.filter(id=>revisions.some(r=>r[0]===id)))]:[],mocks:cleanMocks(s?.mocks),logs:cleanLogs(s?.logs),rest:Array.isArray(s?.rest)?s.rest.filter(x=>typeof x==='string'):[]}};

export default function Home(){
 const [tab,setTab]=useState('Dashboard'),[readDone,setReadDone]=useState([]),[revDone,setRevDone]=useState([]),[mocks,setMocks]=useState(freshMocks),[logs,setLogs]=useState([]),[rest,setRest]=useState([]),[logDate,setLogDate]=useState(iso()),[logHours,setLogHours]=useState(''),[logTopic,setLogTopic]=useState('quantitativeMethods'),[logFocus,setLogFocus]=useState(''),[dialog,setDialog]=useState(null),[score,setScore]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{try{const current=window.localStorage.getItem(STORE),legacy=window.localStorage.getItem(LEGACY_STORE),s=JSON.parse(current||legacy||'{}'),migrated=migrateState(s);setReadDone(migrated.readDone);setRevDone(migrated.revDone);setMocks(migrated.mocks);setLogs(migrated.logs);setRest(migrated.rest);setReady(true);window.localStorage.setItem(STORE,JSON.stringify(migrated))}catch{setReadDone([]);setRevDone([]);setMocks(freshMocks());setLogs([]);setRest([]);setReady(true)}},[]);
 useEffect(()=>{if(ready)try{window.localStorage.setItem(STORE,JSON.stringify({readDone,revDone,mocks,logs,rest}))}catch{}},[readDone,revDone,mocks,logs,rest,ready]);
 const today=new Date(),exam=new Date('2027-08-15T00:00:00'),days=Math.max(0,Math.ceil((exam-today)/86400000)),phase=phaseFor(today);
 const readingPct=readDone.length/10*100,revisionPct=revDone.length/4*100,mockDone=mocks.filter(Boolean).filter(m=>m.done).length,mockPct=mockDone/12*100;
 const weightedFirst=readings.reduce((sum,r)=>sum+(readDone.includes(r[0])?(r[4]/TOTAL_WEIGHT)*50:0),0);
 const weighted={first:weightedFirst,revision:revDone.length/4*20,mocks:mockDone/12*30,total:weightedFirst+revDone.length/4*20+mockDone/12*30};
 const studyHours=logs.reduce((s,x)=>s+Number(x?.hours||0),0),ws=weekStart(today),we=new Date(ws);we.setDate(we.getDate()+7);const weekHours=logs.filter(x=>{const d=parse(x.date);return d>=ws&&d<we}).reduce((s,x)=>s+Number(x?.hours||0),0);
 const streak=(()=>{let n=0,d=new Date();d.setHours(12,0,0,0);for(let i=0;i<365;i++){const k=d.toISOString().slice(0,10),active=logs.some(x=>x?.date===k&&Number(x?.hours)>0);if(!active&&!rest.includes(k))break;if(active)n++;d.setDate(d.getDate()-1)}return n})();
 const topics=useMemo(()=>readings.map(r=>{const l=logs.filter(x=>x?.topic===r[0]);return{...r,logged:l.reduce((s,x)=>s+Number(x?.hours||0),0),sessions:l.length}}),[logs]);
 const next=readings.find(r=>!readDone.includes(r[0]))||readings[9];
 const weekDays=Array.from({length:7},(_,i)=>{const d=new Date(ws);d.setDate(d.getDate()+i);const k=d.toISOString().slice(0,10);return{k,d,hours:logs.filter(x=>x?.date===k).reduce((s,x)=>s+Number(x?.hours||0),0),rest:rest.includes(k)}});
 const trend=useMemo(()=>mocks.filter(m=>m?.done&&m.completedAt&&Number.isFinite(Number(m.score))).slice().sort((a,b)=>parse(a.completedAt)-parse(b.completedAt)||a.id-b.id),[mocks]);
 const chart={w:920,h:300,l:56,r:24,t:18,b:66},cx=i=>trend.length<2?chart.w/2:chart.l+i*(chart.w-chart.l-chart.r)/(trend.length-1),cy=s=>chart.t+(100-s)*(chart.h-chart.t-chart.b)/100,path=trend.map((m,i)=>`${i?'L':'M'} ${cx(i)} ${cy(Number(m.score))}`).join(' ');
 const addLog=e=>{e.preventDefault();const h=Number(logHours);if(!logDate||!Number.isFinite(h)||h<=0)return;setLogs(x=>[{id:`${Date.now()}-${Math.random()}`,date:logDate,hours:h,topic:normalizeTopic(logTopic),focus:logFocus.trim()},...x]);setLogHours('');setLogFocus('')};
 const deleteLog=id=>setLogs(x=>x.filter(y=>y?.id!==id));
 const toggleRest=k=>setRest(x=>x.includes(k)?x.filter(v=>v!==k):[...x,k]);
 const toggleRead=id=>setReadDone(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const toggleRev=id=>setRevDone(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const toggleMock=id=>{const m=mocks.find(x=>x.id===id);if(!m)return;if(m.done){setMocks(x=>x.map(y=>y.id===id?{...y,done:false,completedAt:''}:y));return}setScore(m.score||'');setDialog(id)};
 const completeMock=()=>{const n=Number(score);if(dialog===null||!Number.isFinite(n)||n<0||n>100)return;setMocks(x=>x.map(m=>m.id===dialog?{...m,score:String(n),done:true,completedAt:iso()}:m));setDialog(null);setScore('')};
 const resetStudy=()=>{if(window.confirm('Reset study data? This clears study sessions, first-pass reading completion, revision completion and rest days.')){setLogs([]);setReadDone([]);setRevDone([]);setRest([])}};
 const resetMocks=()=>{if(window.confirm('Reset mock data? This clears all mock scores, completion states and completion dates.'))setMocks(freshMocks())};
 const selectDay=k=>{setLogDate(k);setTab('Study Log')};
 return <main className="shell">
  <header className="topbar"><div><div className="eyebrow">CFA LEVEL I · AUGUST 2027</div><h1>Study Tracker</h1><p>Plan, execute and measure the roadmap in one place.</p></div><div className="count"><strong>{days}</strong><span>days to exam</span></div></header>
  <nav className="nav" aria-label="Primary navigation">{['Dashboard','Roadmap','Topics','Study Log','Mocks'].map(x=><button type="button" key={x} className={tab===x?'active':''} aria-current={tab===x?'page':undefined} onClick={()=>setTab(x)}>{x}</button>)}</nav>
  {tab==='Dashboard'&&<>
   <section className="hero"><div><span className="pill">{phase[0]}</span><h2>Track what actually earns progress.</h2><p>First Pass is weighted by the official Level I topic ranges, Revision is 20%, and the 12 mocks are 30%.</p><div className="heroSummary"><span><span className="legendDot first" aria-hidden="true"/>First Pass <span className="heroMetric">{weighted.first.toFixed(1)}%</span><span className="heroMeta">earned / 50%</span></span><span><span className="legendDot rev" aria-hidden="true"/>Revision <span className="heroMetric">{weighted.revision.toFixed(1)}%</span><span className="heroMeta">earned / 20%</span></span><span><span className="legendDot mockMetric" aria-hidden="true"/>Mocks <span className="heroMetric">{weighted.mocks.toFixed(1)}%</span><span className="heroMeta">earned / 30%</span></span></div></div><div className="readinessWrap"><div className="weightedRing" role="img" aria-label={`${Math.round(weighted.total)} percent exam readiness`} style={{'--first':`${weighted.first}%`,'--revEnd':`${weighted.first+weighted.revision}%`,'--total':`${weighted.total}%`}}><div><span className="ringValue">{Math.round(weighted.total)}%</span><span>readiness</span></div></div><div className="ringCaption">100% = exam readiness</div></div></section>
   <section className="readinessBreakdown" aria-labelledby="readiness-breakdown-title"><div className="breakHead"><div><span className="sectionLabel" id="readiness-breakdown-title">READINESS BREAKDOWN</span><h3>Official topic weights, not equal modules</h3></div><span className="breakTotal">{Math.round(weighted.total)} / 100</span></div><SegmentBar count={10} done={readDone.length} label="First Pass" weight="50%" color="first" note="Weighted by CFA topic range midpoints"/><SegmentBar count={4} done={revDone.length} label="Revision" weight="20%" color="rev" note="4 equal revision blocks"/><SegmentBar count={12} done={mockDone} label="Mocks" weight="30%" color="mock" note="12 equal mock attempts"/></section>
   <div className="grid four"><KpiCard label="Overall readiness" value={`${Math.round(weighted.total)}%`} sub="Actual readiness earned" tone="blue"/><KpiCard label="First Pass" value={`${readDone.length}/10`} sub={`${Math.round(readingPct)}% topics complete · ${weighted.first.toFixed(1)}% earned`} tone="cyan"/><KpiCard label="Revision" value={`${revDone.length}/4`} sub={`${Math.round(revisionPct)}% complete · ${weighted.revision.toFixed(1)}% earned`} tone="purple"/><KpiCard label="Mocks" value={`${mockDone}/12`} sub={`${Math.round(mockPct)}% complete · ${weighted.mocks.toFixed(1)}% earned`} tone="orange"/></div>
   <div className="dashboardGrid"><section className="panel"><div className="panelHead"><div><span className="sectionLabel">EXECUTION</span><h3>This week</h3><p>{weekHours}h logged · {phase[1]}h target · {streak} day streak</p></div></div><div className="weekGrid" aria-label="Weekly study execution">{weekDays.map(x=><button type="button" className={`dayCell ${x.rest?'rest':''}`} key={x.k} aria-label={`${x.d.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'short'})}. ${x.rest?'Rest day.':x.hours?`${x.hours} hours studied.`:'No study hours logged.'} Open study log.`} onClick={()=>selectDay(x.k)}><span className="dayName">{x.d.toLocaleDateString('en-IN',{weekday:'short'})}</span><span className="dayHours">{x.hours?`${x.hours}h`:'—'}</span><span className="dayState">{x.rest?'Rest':x.hours?'Studied':'Open'}</span></button>)}</div></section><section className="panel"><div className="panelHead"><div><span className="sectionLabel">NEXT TOPIC</span><h3>{next[1]}</h3><p>{next[3]}h planned · {next[2]}</p></div><button className="primary" type="button" onClick={()=>{setLogTopic(next[0]);setTab('Study Log')}}>Log session</button></div><div className={`nextState ${readDone.includes(next[0])?'complete':''}`}><span className="statusDot" aria-hidden="true"/> <span>{readDone.includes(next[0])?'Reading complete':'Reading open'}</span> <span className="nextContribution">{(next[4]/TOTAL_WEIGHT*50).toFixed(1)}% readiness</span></div></section></div>
   <section className="panel"><div className="panelHead"><div><span className="sectionLabel">MOCK READINESS · 30%</span><h3>Score trend</h3><p>{trend.length?'Actual completion dates are plotted below.':'Complete mocks to build the dated line chart.'}</p></div><button className="primary" type="button" onClick={()=>setTab('Mocks')}>Open mocks</button></div>{trend.length?<LineChart points={trend} chart={chart} cx={cx} cy={cy} path={path}/>:<div className="chartEmpty">No completed mock scores yet.</div>}</section>
  </>}
  {tab==='Roadmap'&&<section className="panel"><div className="panelHead"><div><span className="sectionLabel">WEIGHTED ROADMAP</span><h2>10 Official Level I Topics</h2><p>FSA and Fixed Income are each a single CFA topic. Their internal study time is consolidated into one trackable topic.</p></div><span className="pill">{weighted.first.toFixed(1)}% first pass earned</span></div><div className="phaseBanner first"><div><span className="phaseTitle">FIRST PASS · 50%</span><span>{readDone.length}/10 topics complete · {weighted.first.toFixed(1)}% earned</span></div><span className="phaseBadge">WEIGHTED</span></div>{readings.map(r=>{const d=readDone.includes(r[0]),contrib=r[4]/TOTAL_WEIGHT*50;return <div className={`road ${d?'isDone':''}`} key={r[0]}><button type="button" className={`check ${d?'done':''}`} aria-label={`${d?'Mark':'Mark'} ${r[1]} ${d?'incomplete':'complete'}`} aria-pressed={d} onClick={()=>toggleRead(r[0])}>{d?'✓':''}</button><div className="roadDate">{r[2]}</div><div className="roadMain"><span className="roadTopic">{r[1]}</span><span>{r[3]}h planned · {r[4].toFixed(1)}% curriculum midpoint</span></div><div className="roadHours"><span className="roadStatus">{d?'Complete':'Open'}</span><span className="roadContribution">+{contrib.toFixed(1)}% readiness</span></div></div>})}<div className="subsection"><div className="phaseBanner rev"><div><span className="phaseTitle">REVISION · 20%</span><span>{revDone.length}/4 blocks complete · {weighted.revision.toFixed(1)}% earned</span></div><span className="phaseBadge">EQUAL BLOCKS</span></div>{revisions.map(r=>{const d=revDone.includes(r[0]);return <div className={`revision ${d?'isDone':''}`} key={r[0]}><button type="button" className={`check ${d?'done':''}`} aria-label={`${d?'Mark':'Mark'} revision block ${r[1]} ${d?'incomplete':'complete'}`} aria-pressed={d} onClick={()=>toggleRev(r[0])}>{d?'✓':''}</button><div><span className="revisionTitle">{r[1]}</span><span>{r[2]}</span></div><p>{r[3]}</p><span className="revisionEarned">{d?'5.0% earned':'5.0% available'}</span></div>})}</div></section>}
  {tab==='Topics'&&<section className="panel"><div className="panelHead"><div><span className="sectionLabel">TOPICS</span><h2>Topic execution</h2><p>Each CFA topic is shown once. Study Log hours feed the execution bar; the completion check earns weighted First Pass readiness.</p></div><button className="ghost" type="button" onClick={resetStudy}>Reset study data</button></div><div className="topicGrid">{topics.map(r=>{const d=readDone.includes(r[0]),hp=Math.min(100,Math.round(r.logged/r[3]*100)),contrib=r[4]/TOTAL_WEIGHT*50;return <article className={`topic ${d?'topicDone':''}`} key={r[0]}><div className="topicTop"><div><span className="topicTitle">{r[1]}</span><span>{r.logged}h / {r[3]}h planned · {r.sessions} sessions</span></div><span className={`status ${d?'doneText':''}`}>{d?'TOPIC COMPLETE':'TOPIC OPEN'}</span></div><div className="bar" role="progressbar" aria-label={`${r[1]} study hours`} aria-valuenow={hp} aria-valuemin="0" aria-valuemax="100" aria-valuetext={`${hp}% of planned study hours logged`}><span className="barFill" style={{width:`${hp}%`}} aria-hidden="true"/></div><div className="topicFooter"><span>{hp}% hours logged</span><span className="readinessContribution">{d?`+${contrib.toFixed(1)}% readiness earned`:`+${contrib.toFixed(1)}% available`}</span></div><div className="topicActions"><button type="button" onClick={()=>{setLogTopic(r[0]);setTab('Study Log')}}>Log session</button><button type="button" onClick={()=>toggleRead(r[0])}>{d?'Undo completion':'Mark topic complete'}</button></div></article>})}</div></section>}
  {tab==='Study Log'&&<section className="panel"><div className="panelHead"><div><span className="sectionLabel">EXECUTION LOG</span><h2>Study Log</h2><p>Log study time against the 10 official CFA Level I topics.</p></div><button className="ghost" type="button" onClick={resetStudy}>Reset study data</button></div><div className="logNotice"><span className="noticeIcon" aria-hidden="true">i</span><div><span className="noticeTitle">Readings are consolidated by official topic</span><p>Financial Statement Analysis and Fixed Income are each one topic here. Their historical split is migrated into the single topic automatically. <span className="noticeEmphasis">Hours logged</span> track execution; <span className="noticeEmphasis">topic completion</span> changes weighted readiness.</p></div></div><form className="logForm" onSubmit={addLog}><label>Date<input type="date" value={logDate} onChange={e=>setLogDate(e.target.value)}/></label><label>Hours<input type="number" min="0.25" step="0.25" value={logHours} onChange={e=>setLogHours(e.target.value)} placeholder="2.5"/></label><label>Topic<select value={logTopic} onChange={e=>setLogTopic(e.target.value)}>{readings.map(r=><option value={r[0]} key={r[0]}>{r[1]}</option>)}</select></label><label className="wide">Focus / notes<input value={logFocus} onChange={e=>setLogFocus(e.target.value)} placeholder="TVM practice, questions, review…"/></label><button className="primary" type="submit">Add session</button></form><div className="weekStats">{[['Total study',studyHours],['This week',weekHours],['Weekly target',phase[1]],['Study streak',streak]].map(([label,value])=><div key={label}><span className="statValue">{value}{label!=='Study streak'?'h':''}</span><span className="statLabel">{label}</span></div>)}</div><div className="dayPlanner">{weekDays.map(x=><div className={`dayPlan ${x.rest?'rest':''}`} key={x.k}><div><span className="dayPlanName">{x.d.toLocaleDateString('en-IN',{weekday:'short'})}</span><span>{x.d.toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</span></div><span className="dayPlanHours">{x.hours}h</span><button type="button" onClick={()=>toggleRest(x.k)} aria-pressed={x.rest}>{x.rest?'Remove rest':'Mark rest'}</button></div>)}</div><div className="logList">{logs.length?logs.map(x=><div className="logRow" key={x.id}><span>{fmt(x.date)}</span><span className="logHoursValue">{x.hours}h</span><span>{readings.find(r=>r[0]===x.topic)?.[1]||x.topic}</span><span>{x.focus||'—'}</span><button type="button" onClick={()=>deleteLog(x.id)} aria-label={`Delete study session from ${fmt(x.date)}`}>×</button></div>):<div className="empty">No study sessions logged yet.</div>}</div></section>}
  {tab==='Mocks'&&<section className="panel"><div className="panelHead"><div><span className="sectionLabel">PHASE 3 · 30%</span><h2>12-Mock Gauntlet</h2><p>Each completed mock contributes exactly 2.5% of overall readiness.</p></div><button className="ghost" type="button" onClick={resetMocks}>Reset mock data</button></div><div className="mockGrid">{mocks.map(m=><article className={`mock ${m.done?'mockDone':''}`} key={m.id}><div className="mockTop"><div><span>MOCK {m.id}</span><span className="mockDate">{fmt(m.date)}</span></div><button type="button" className={`check ${m.done?'done':''}`} aria-label={`${m.done?'Mark':'Mark'} Mock ${m.id} ${m.done?'incomplete':'completed'}`} aria-pressed={m.done} onClick={()=>toggleMock(m.id)}>{m.done?'✓':''}</button></div>{m.done?<div className="mockScore"><span className="mockScoreValue">{m.score}%</span><span>Completed {fmt(m.completedAt)} · +2.5% readiness</span></div>:<div className="mockScore"><span>Not completed · +2.5% available</span></div>}<button className="ghost mockAction" type="button" onClick={()=>toggleMock(m.id)}>{m.done?'Mark incomplete':'Mark completed'}</button></article>)}</div>{trend.length?<LineChart points={trend} chart={chart} cx={cx} cy={cy} path={path}/>:null}</section>}
  {dialog!==null&&<div className="modalBackdrop" role="presentation"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="mock-dialog-title"><span className="sectionLabel">COMPLETE MOCK {dialog}</span><h2 id="mock-dialog-title">Enter mock score</h2><p>The score is required. Today's date will automatically be saved as the completion date.</p><label>Score (%)<input autoFocus type="number" min="0" max="100" value={score} onChange={e=>setScore(e.target.value)} placeholder="e.g. 72"/></label><div className="modalActions"><button className="ghost" type="button" onClick={()=>{setDialog(null);setScore('')}}>Cancel</button><button className="primary" type="button" disabled={score===''||!Number.isFinite(Number(score))||Number(score)<0||Number(score)>100} onClick={completeMock}>Complete mock</button></div></div></div>}
  <footer><span>Overall readiness = weighted First Pass 50% + Revision 20% + Mocks 30%</span><span>Study data stored in this browser</span></footer>
 </main>;
}
function KpiCard({label,value,sub,tone}){return <article className={`card tone-${tone}`}><span>{label}</span><span className="kpiValue">{value}</span><span className="kpiSub">{sub}</span></article>}
function SegmentBar({count,done,label,weight,color,note}){const pct=count?Math.min(100,(done/count)*100):0;const metricClass=color==='mock'?'mockMetric':color;return <div className="segmentRow"><div className="segmentLabel"><span><span className={`legendDot ${metricClass}`} aria-hidden="true"/>{label}</span><span className="segmentCount">{done}/{count}</span><span className="segmentNote">{weight} · {note}</span></div><div className="segments" role="progressbar" aria-label={`${label} progress`} aria-valuenow={done} aria-valuemin="0" aria-valuemax={count} aria-valuetext={`${done} of ${count} complete`}>{Array.from({length:count},(_,i)=><span className={`segment ${i<done?'filled':''} ${metricClass}`} key={i} aria-hidden="true"/>)}<span className="srOnly">{done} of {count} complete ({pct.toFixed(0)}%).</span></div></div>}
function LineChart({points,chart,cx,cy,path}){const label=points.length?`Mock score trend with ${points.length} completed mocks. Average score ${Math.round(points.reduce((s,p)=>s+Number(p.score),0)/points.length)} percent.`:'Mock score trend';return <div className="lineChartWrap"><svg className="lineChart" viewBox={`0 0 ${chart.w} ${chart.h}`} role="img" aria-label={label}>{[0,25,50,75,100].map(v=><g key={v}><line className="gridLine" x1={chart.l} x2={chart.w-chart.r} y1={cy(v)} y2={cy(v)}/><text className="axisText" x={chart.l-12} y={cy(v)+4} textAnchor="end">{v}</text></g>)}{points.length>1&&<path d={path} fill="none" stroke="#67dfcf" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"/>}{points.map((p,i)=><g key={`${p.id}-${p.completedAt}`}><circle className="chartDot" cx={cx(i)} cy={cy(Number(p.score))} r="5"/><text className="scoreText" x={cx(i)} y={cy(Number(p.score))-11} textAnchor="middle">{p.score}%</text><text className="dateText" x={cx(i)} y={chart.h-28} textAnchor="middle">{fmt(p.completedAt)}</text><text className="dateText" x={cx(i)} y={chart.h-12} textAnchor="middle">Mock {p.id}</text></g>)}</svg></div>}
